### ISSUE TITLE
robot_simulation directory is empty

### ISSUE THREAD

**Issue by kimkimyoung** [enginksz/imitation_learning_ros#1]
Thanks for sharing your work.
The robot_simulation directory is empty, how to run the simulation?

**Comment by enginksz** [comment]
Hi,

	1.	mkdir imitation_learning_ros
Creates a new folder called imitation_learning_ros or workspace projects folder.

	2.	Copy **src** to **imitation_learning_ros**
Copies the src folder to the imitation_learning_ros directory.

	3.	cd imitation_learning_ros
Switches to the imitation_learning_ros folder.

	4.	colcon build

   5. source install/setup.bash

Loads ROS 2 environment variables.

	6.	ros2 launch robot_gazebo main.launch.xml
Launches the robot simulation in Gazebo using the specified launch file.

**Comment by kimkimyoung** [comment]
![image](https://github.com/user-attachments/assets/df8fc0ec-67ad-43ae-b710-0517957f65d7)
Thanks for reply. I understand the flow. But seems the robot_gazebo ros package is empty. So it can not be launched.

**Comment by enginksz** [comment]
Yes, you are right, I will upload it as soon as possible. 
Thank you for your attention.

**Comment by kimkimyoung** [comment]
Thanks ! you are so nice !
